var ast = BSParser.matchAll('
module m1{
env {
  type : server
}

import m1;
import m2.m3;

object bl { 
  private foobar , bar1;
  private baz = "3";
  private function doIt() { 
    blah
  }

  protected baz = "3";
  protected function doIt() { 
    blah
  }

  baz = "3";
  function doIt() { 
    blah
  }
}

private function f1() {
  baz
}

public function f2() {
  baz
}

function f3() {
  baz
}

}',"compilationUnit");
alert(ast);